name: Taiga
description: |
Taiga is a project management platform for startups and agile developers & designers who want a simple, beautiful tool that makes work truly enjoyable.
version: latest
category: Continuous Integration
